FROM docker.io/library/debian:trixie-slim

RUN dpkg --add-architecture arm64 \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        ca-certificates \
        bison \
        gcc-aarch64-linux-gnu \
        gawk \
        libc6-dev-arm64-cross \
        libfontconfig1-dev:arm64 \
        libfreetype-dev:arm64 \
        libx11-dev:arm64 \
        libx11-xcb-dev:arm64 \
        libxext-dev:arm64 \
        libxfixes-dev:arm64 \
        libxi-dev:arm64 \
        libxrandr-dev:arm64 \
        libxrender-dev:arm64 \
        libxft-dev:arm64 \
        libxkbcommon-x11-dev:arm64 \
        fonts-liberation \
        make \
        patch \
        python3 \
        texinfo \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /work
